### ISSUE TITLE
[Feature] 질문 게시판 질문 목록 생성 - cs, 인성

### ISSUE THREAD

**Issue by jang643** [employment-rocket/rocket#10]
## 📝 Description
질문 목록 생성 및 선택 기능 추가

## 📍 Todo
- [x] 백엔드 답변 테이블 및 컨트롤러, 서비스 등 생성
- [x] 백엔드 질문 카테고리 별 도메인 구현
- [x] 프론트 엔드 컴포넌트 생성
- [x] api 연동
