### ISSUE TITLE
[Fix] 일정관리 피드백 반영

### ISSUE THREAD

**Issue by wjdrltjr5** [employment-rocket/rocket#15]
## 📝 Description
12-27일 회의록에 작성한 피드백 반영하기

## 📍 Todo
- [x] 카테고리 디자인 수정
- [x] 일정관리 드래그 존 디자인 수정
- [x] 타입수정(ex 서류->1차) 했을때 바로 정렬되게 수정
